version: "3.7"

services:
  app:
    build: ./
    restart: always
    ports:
      - 3000:3000
    environment:
      - DBHOST=redis
    depends_on:
      - redis

  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - ./data:/data
